eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
server:
  port: 8082
spring:
  application:
    name: service-provider

myInfo:
    macAdd: provider-A_8082
    requestMappingName0: /testUser
    requestUrl0: http://localhost:8080/demo/addUserInter
    forServer: http://localhost:8080/demo/



