spring:
 datasource:
  name: lgz
  url: jdbc:mysql://localhost:3306/lgz
  username: root
  password: lgz@168168
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.demo.bean